// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';

  /**
    * @ngdoc directive
    * @name unuApp.directive:ValidateUnique
    * @description
    * # ValidateUnique
   */
  angular.module('unuApp').directive('validateUnique', function(Restangular) {
    return {
      require: 'ngModel',
      scope: {
        attribute: '@',
        minlengthvalidation: '@',
        queryModel: '@',
        url: '@'
      },
      link: function(scope, element, attrs, ctrl) {
        scope.minlengthvalidation = scope.minlengthvalidation || 0;
        return ctrl.$parsers.unshift(function(value) {

          var localService;
          if (value.length >= scope.minlengthvalidation) {
            localService = Restangular.all(scope.queryModel);
              localService.customGET('/methods/validate-unique', {
                value: value,
                attribute:scope.attribute
              }).then(function(result) {
                if (result.success) {
                  return ctrl.$setValidity('validateUnique', true);
                } else {
                  return ctrl.$setValidity('validateUnique', false);
                }
              });
          } else {
            ctrl.$setValidity('validateUnique', true);
          }
          return value;
        });
      }
    };
  });

}).call(this);
