// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name unuApp.controller:AppCtrl
    * @description
    * # AppCtrl
    * Controller of the unuApp
   */
  angular.module('unuApp')
  .controller('AppCtrl', ['$scope', 'UserFactory', '$rootScope', '$mdSidenav', '$log', '$state',function($scope, UserFactory, $rootScope, $mdSidenav, $log, $state) {
    $rootScope.app.module ='';
    $rootScope.menu = UserFactory.getAccess();
    $scope.GoTo = function(item) {
      $rootScope.app.module = ' > ' + item.title;
      $state.go(item.url);
      return console.log(item.url);
    };
    $scope.SidenavToggle = function() {
      return $mdSidenav('left').toggle().then(function() {
        $log.debug('close sidenav');
      });
    };
    $scope.Logout = function() {
      UserFactory.logout();
    };

  }]);

})();
