// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name unuApp.controller:ArchivosBancoSalidaCtrls
    * @description
    * # ArchivosBancoSalidaCtrl
    * Controller of the unuApp
   */
  angular.module('unuApp').controller('ArchivosBancoSalidaCtrl', [
    'MessageFactory','$sce', '$rootScope', '$scope', 'Restangular', '$mdDialog', '$timeout', 'ngTableParams',
  function(MessageFactory, $sce,$rootScope, $scope, Restangular, $mdDialog, $timeout, ngTableParams) {
    var List, service;

    $scope.UI = {
      refresh: false,
      message: MessageFactory,
      title: 'Listado de Archivos Salida',
      editMode: false,
      selected:null,
      customActions:[]
    };

    var LOCAL ={
      name: 'ArchivosSalida',
      form:'',
      route:'archivobancos'
    };
    service = Restangular.all(LOCAL.route);
    $rootScope.app.module = ' > ' + LOCAL.name;

    List = function() {
      $scope.tableParams = new ngTableParams({
        page: 1,
        count: 10,
        filter:{
          tipo: 'S'
        }
      }, {
        total: 0,
        getData: function($defer, params) {
          var query;
          query = params.url();
          $scope.UI.refresh = true;
          service.customGET('methods/paginate', query).then(function(result) {
            $timeout(function() {
              params.total(result.total);
              $defer.resolve(result.data);
              $scope.UI.refresh = false;
            }, 500);
          });
        }
      });
    };

    $scope.Refresh = function Refresh(){
      $scope.UI.selected = null;
      $scope.UI.editMode = false;
      $scope.tableParams.reload();
    };
    var archivoService = Restangular.all('archivobancos');

    $scope.EnabledEdit =function EnabledEdit(item){
      $scope.UI.editMode = false;
      $scope.UI.selected = null;
      angular.forEach($scope.tableParams.data,function(element){
        if(item._id !== element._id){
          element.active = false;
        }
      });

      if( item.active ){
        $scope.URL_SERVER = $sce.trustAsResourceUrl(archivoService.getRestangularUrl() + '/methods/download/'+item.nombre)
        $scope.UI.editMode = true;
        $scope.UI.selected = item;
        $scope.UI.selected.route = LOCAL.route;
      }
    };

    $scope.DownloadFile = function DownloadFile($event){

      var nomArchivo = $scope.UI.selected.nombre;
      $('#btnDownloadArchivo').click();
      /*service.customPOST('methods/download', {nombreArchivo:nomArchivo}).then(function(result) {
        $timeout(function() {

        }, 500);
      });*/
    };

    $scope.GenerateFile = function GenerateFile($event){
      var confirm = $mdDialog.confirm()
          .title(LOCAL.name)
          .content('Desea generar el archivo con los compromisos de pago?')
          .ariaLabel(LOCAL.name)
          .targetEvent($event)
          .ok(MessageFactory.Buttons.Yes)
          .cancel(MessageFactory.Buttons.No);

      $mdDialog.show(confirm).then(function() {
        $('#btnDownloadRecaudo').click();

      }, function() {

      });
    };

    new List();
    /*
    $scope.New = function New($event){
      var parentEl = angular.element(document.body);
      $mdDialog.show({
        parent: parentEl,
        targetEvent: $event,
        templateUrl :LOCAL.form,
        locals:{
          name: LOCAL.name,
          table:$scope.tableParams,
          service: service
        },
        controller: 'AulaNewCtrl'
      });
    };
    $scope.Edit = function Edit($event){
      var parentEl = angular.element(document.body);
      $mdDialog.show({
        parent: parentEl,
        targetEvent: $event,
        templateUrl :LOCAL.form,
        locals:{
          name: LOCAL.name,
          table:$scope.tableParams,
          model: Restangular.copy($scope.UI.selected)
        },
        controller: 'AulaEditCtrl'
      });
    };

    $scope.Delete = function Delete($event){
      var confirm = $mdDialog.confirm()
          .title(LOCAL.name)
          .content(MessageFactory.Form.QuestionDelete)
          .ariaLabel(LOCAL.name)
          .targetEvent($event)
          .ok(MessageFactory.Buttons.Yes)
          .cancel(MessageFactory.Buttons.No);

      var selected = Restangular.copy($scope.UI.selected);

      $mdDialog.show(confirm).then(function() {
        selected.remove().then(function() {
          $scope.Refresh();
          ToastMD.success(MessageFactory.Form.Deleted);
        });
      }, function() {

      });
    };
    */
  }]);

}).call(this);
