// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name unuApp.controller:AulasCtrl
    * @description
    * # AulasCtrl
    * Controller of the unuApp
   */
  angular.module('unuApp').controller('AsignarAulasCtrl', function(MessageFactory, $rootScope, $scope, Restangular, $mdDialog, $timeout, LxDialogService, LxNotificationService, $mdBottomSheet, $state) {
    var List, service;

    var LoadPabellones = function LoadPabellones() {
      var servicePabellones = Restangular.all('facultades');
      serviceFacultad.getList().then(function(data){
        $scope.facultades = data;
      });
    };

    $scope.horarios = [
      {ini: '7:00 am', fin: '8:00 am'},
      {ini: '8:00 am', fin: '9:00 am'},
      {ini: '9:00 am', fin: '10:00 am'},
      {ini: '10:00 am', fin: '11:00 am'},
      {ini: '11:00 am', fin: '12:00 am'},
      {ini: '12:00 am', fin: '1:00 pm'},
      {ini: '2:00 am', fin: '3:00 am'},
      {ini: '3:00 am', fin: '4:00 am'},
      {ini: '4:00 am', fin: '5:00 am'},
      {ini: '5:00 am', fin: '6:00 am'},
      {ini: '6:00 am', fin: '7:00 am'},
      {ini: '7:00 am', fin: '8:00 am'},
      {ini: '8:00 am', fin: '9:00 am'},
      {ini: '9:00 am', fin: '10:00 am'},
      {ini: '10:00 am', fin: '11:00 am'}
    ];

    $scope.pabellones = [];

    $scope.UI = {
      refresh: false,
      message: MessageFactory,
      title: 'Asignación de Aulas',
      editMode: false,
      selected:null,
      customActions:[]
    };

    var LOCAL ={
      name: 'Asignación de Aulas',
      form:'views/asignaraulas/index.html',
      route:'asignaraulas',
      route_facultades: 'facultades',
      route_escuelas: 'escuelas'
    };
    service = Restangular.all(LOCAL.route);
    $rootScope.app.module = ' > ' + LOCAL.name;

    var service_facultades = Restangular.all(LOCAL.route_facultades);

    $scope.handleCell = function(hora, aula){
      alert(hora.ini + ' - ' + hora.fin + ' - ' + aula);
    };

  });

}).call(this);
