// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';

  /**
   * @ngdoc function
   * @name unuApp.controller:PlanestudiosCtrl
   * @description
   * # PlanestudiosCtrl
   * Controller of the unuApp
   */

  angular.module('unuApp').controller('FacultadProcesosCtrl', [
    '$mdSidenav', '$q', 'MessageFactory', '$rootScope', '$scope', 'Restangular', '$mdDialog', '$timeout', 'NgTableParams', 'LxDialogService', 'ToastMD',  '$state',
    function($mdSidenav, $q, MessageFactory, $rootScope, $scope, Restangular, $mdDialog, $timeout, NgTableParams, LxDialogService, ToastMD, $state) {
      var List, serviceProcesoFacultad, serviceParametroEscuela;

      $scope.UI = {
        refresh: false,
        message: MessageFactory,
        title: 'Registro de Procesos por Facultad',
        editMode: false,
        selected: null,
        customActions: []
      };

      var LOCAL = {
        name: 'Procesos por Facultad',
        form: 'views/facultades/procesos-form.html',
        routeProcesos: 'procesofacultades'
      };

      serviceProcesoFacultad = Restangular.all(LOCAL.routeProcesos);
      $rootScope.app.module = ' > ' + LOCAL.name;

      var LoadFacultades = function LoadFacultades() {
        var serviceFacultad = Restangular.all('facultades');
        serviceFacultad.getList().then(function(data) {
          $scope.facultades = data;
        });
      };

      $scope.LoadProcesosFacultad = function LoadProcesosFacultad() {
        if($scope.filter.hasOwnProperty('_facultad') && $scope.filter.hasOwnProperty('_periodo')){
          var serviceProcesoFacultad = Restangular.all('procesofacultades');
          serviceProcesoFacultad.getList({
            populate:'_proceso _facultad _periodo',
            conditions: {
              _facultad: $scope.filter._facultad._id,
              _periodo: $scope.filter._periodo._id
            }
          }).then(function(data) {
            $scope.procesosFacultad = data;
          });
        }
      };

      var LoadPeriodos = function LoadPeriodos() {
        var servicePeriodo = Restangular.all('periodos');
        servicePeriodo.getList().then(function(data) {
          $scope.periodos = data;
        });
      };
      new LoadPeriodos();
      new LoadFacultades();



      $scope.filter = {};
      $scope.New = function New($event) {
        if (!$scope.filter._facultad) {
          ToastMD.warning('Debe seleccionar una facultad antes de agregar un proceso');
          return;
        }
        if (!$scope.filter._periodo) {
          ToastMD.warning('Debe seleccionar un periodo antes de crear un proceso');
          return;
        }

        var parentEl = angular.element(document.body);
        $mdDialog.show({
          parent: parentEl,
          targetEvent: $event,
          templateUrl: LOCAL.form,
          locals: {
            selectedTab: $scope.selectedTab,
            name: LOCAL.name,
            table: $scope.LoadProcesosFacultad,
            facultad: $scope.filter._facultad,
            periodo: $scope.filter._periodo,
            serviceProcesoFacultad: serviceProcesoFacultad
          },
          controller: 'FacultadProcesosNewCtrl'
        });
      };
      $scope.Edit = function Edit($event) {
        var parentEl = angular.element(document.body);
        $mdDialog.show({
          parent: parentEl,
          targetEvent: $event,
          templateUrl: LOCAL.form,
          locals: {
            name: LOCAL.name,
            table: $scope.LoadProcesosFacultad,
            model: Restangular.copy($scope.UI.selected),
            facultad: $scope.filter._facultad
          },
          controller: 'FacultadProcesosEditCtrl'
        });
      };

      $scope.Delete = function Delete($event) {
        var confirm = $mdDialog.confirm()
          .title(LOCAL.name)
          .content(MessageFactory.Form.QuestionDelete)
          .ariaLabel(LOCAL.name)
          .targetEvent($event)
          .ok(MessageFactory.Buttons.Yes)
          .cancel(MessageFactory.Buttons.No);

        var selected = Restangular.copy($scope.UI.selected);
        selected.route = 'procesofacultades';
        $mdDialog.show(confirm).then(function() {
          selected.remove().then(function() {
            $scope.LoadProcesosFacultad();
            ToastMD.success(MessageFactory.Form.Deleted);
          });
        }, function() {

        });
      };

      $scope.EnabledEdit = function EnabledEdit(item) {
        $scope.UI.editMode = false;
        $scope.UI.selected = null;
        angular.forEach($scope.procesosFacultad, function(element) {
          if (item._id !== element._id) {
            element.active = false;
          }
        });

        if (item.active) {
          $scope.UI.editMode = true;
          $scope.UI.selected = item;
          $scope.UI.selected.route = LOCAL.route;
        }
      };

    }
  ])

  .controller('FacultadProcesosNewCtrl', [
      '$scope', 'name', 'table', 'facultad', 'periodo', 'selectedTab', 'serviceProcesoFacultad', 'MessageFactory', 'Restangular', 'ToastMD', '$mdDialog',
      function($scope, name, table, facultad, periodo, selectedTab,  serviceProcesoFacultad, MessageFactory, Restangular, ToastMD, $mdDialog) {
        $scope._facultad = facultad;
        $scope._periodo = periodo;
        $scope.submited = false;
        $scope.title = MessageFactory.Form.New.replace('{element}', name);
        $scope.Buttons = MessageFactory.Buttons;
        $scope.message = MessageFactory.Form;

        $scope.model = {
          _facultad: facultad._id,
          _periodo: periodo._id
        };

        $scope.Cancel = function() {
          $mdDialog.hide();
        };

        Restangular.all('procesos').getList({sort:'nombre'}).then(function(data) {
          $scope.procesos = data;
        });
        $scope.Save = function(form) {
          $scope.submited = true;
          if (form.$valid) {
            serviceProcesoFacultad.post($scope.model).then(function() {
              ToastMD.success(MessageFactory.Form.Saved);
              $mdDialog.hide();
              table();
            });
          }
        };

        }

    ])
    .controller('FacultadProcesosEditCtrl', ['$scope', 'table', 'name', 'model', 'facultad', 'MessageFactory', 'Restangular', 'ToastMD', '$mdDialog',
      function($scope, table, name, model, facultad, MessageFactory, Restangular, ToastMD, $mdDialog) {
        $scope._facultad = model._facultad;
        $scope._periodo = model._periodo;
        $scope.submited = false;
        $scope.model = model ;
        $scope.model.fechaInicio = new Date(model.fechaInicio) ;
        $scope.model.fechaFin = new Date(model.fechaFin) ;
        $scope.model.route = 'procesofacultades';
        $scope.title = MessageFactory.Form.Edit.replace('{element}', name);
        $scope.Buttons = MessageFactory.Buttons;
        Restangular.all('procesos').getList({sort:'nombre'}).then(function(data) {
          $scope.procesos = data;
        });
        $scope.Save = function(form) {
          $scope.submited = true;
          if (form.$valid) {
            $scope.model.put().then(function() {
              ToastMD.success(MessageFactory.Form.Updated);
              $mdDialog.hide();
              table();
            });
          }
        };
        $scope.Cancel = function() {
          $mdDialog.hide();
        };
      }
    ]);

}).call(this);
