// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';

  /**
   * @ngdoc function
   * @name unuApp.controller:LoginCtrl
   * @description
   * # LoginCtrl
   * Controller of the unuApp
   */
  angular.module('unuApp').controller('GetCodeCtrl', [
    '$scope', 'Restangular', '$rootScope','ToastMD',
    function($scope, Restangular, $rootScope, ToastMD) {
        $scope.model = {};

        $scope.ObtenerCodigo = function(){
          var service = Restangular.all('alumnos');
          service.customPOST( $scope.model,'methods/getcode').then(function(result) {
              $scope.codigoAlumno ='Código de alumno es '+result;
              ToastMD.success('Se encontró el alumno con el dni ingresado');
          },function(result){
            $scope.codigoAlumno='';
            console.log(result);
            ToastMD.warning(result.data.message);
          });
        };

    }
  ]);

}).call(this);
