// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';

  /**
   * @ngdoc function
   * @name unuApp.controller:HorariosCtrl
   * @description
   * # HorariosCtrl
   * Controller of the unuApp
   */
  angular.module('unuApp')
    .controller('HorariosCtrl', function(
      $scope,
      MessageFactory,
      Restangular,
      $rootScope,
      $timeout,
      NgTableParams
    ) {

      /**
       * testing
       */
      var nn = Restangular.all('grupocursos');
      nn.getList().then(function( data ){
        console.log('grupo cursos', data);
      });

      /**
       * variables iniciales
       */
      var service,
      serviceFacultad,
      servicePeriodo,
      serviceGrupoCurso,
      servicePlanestudios,
      serviceEscuela;
      var LOCAL = {
        name: 'Gestión de Horarios',
        form: 'views/aprobacion/cursos/form.html',
        route: 'cursoaperturadoperiodos'
      };
      $scope.UI = {
        refresh: false,
        message: MessageFactory,
        title: 'Registro de Horarios para Cursos Aprobados',
        editMode: true,
        selected: null,
        customActions: []
      };

      /**
       * define el endpoint a usar
       */
      service = Restangular.all(LOCAL.route);
      $rootScope.app.module = ' > ' + LOCAL.name;

      /**
       * obtienes los datos iniciales para el filtro
       */
      var LoadFacultades = function LoadFacultades() {
        serviceFacultad = Restangular.all('facultades');
        serviceFacultad.getList().then(function(data) {
          $scope.facultades = data;
        });
      };
      var LoadPeriodos = function LoadPeriodos() {
        servicePeriodo = Restangular.all('periodos');
        servicePeriodo.getList().then(function(data) {
          $scope.periodos = data;
        });
      };
      new LoadFacultades();
      new LoadPeriodos();

      /**
       * funciones llamadas en la vista
       */
      $scope.LoadEscuelas = function LoadEcuelas() {
        serviceEscuela = Restangular.all('escuelas');
        serviceEscuela.getList({
          conditions: {
            _facultad: $scope.filter._facultad._id
          }
        }).then(function(data) {
          $scope.escuelas = data;
        });
      };
      $scope.ListPlanEstudios = function ListPlanEstudios() {
        servicePlanestudios = Restangular.all('planestudios');
        servicePlanestudios.getList({
            conditions: {
              _escuela: $scope.filter._escuela._id
            }
          })
          .then(function(data) {
            $scope.planestudios = data;
          });
      };

      $scope.Refresh = function Refresh() {
        $scope.UI.selected = null;
        $scope.UI.editMode = false;
        $scope.tableParams.reload();
      };

      $scope.filter = {};

      /**
       * lista los cursos, se ejecuta en el ng-change de "Plan Estudios"
       */
      $scope.ListaCursosGrupos = function () {
        /*serviceGrupoCurso = Restangular.all('programaciongrupocursos');
        serviceGrupoCurso.getList().then(function(response){
            console.log('Hola', response);
        });
        return false;*/
        $scope.tableParams = new NgTableParams({
          page: 1,
          count: 1000
        }, {
          total: 0,
          groupBy: 'ciclo',
          counts: [],
          getData: function($defer, params) {
            var query;
            query = params.url();

            $scope.UI.refresh = true;
            service.customGET('methods/paginate', query).then(function(result) {
              $timeout(function() {
                console.log(result);
                params.total(result.total);
                $defer.resolve(result.data);
                $scope.UI.refresh = false;
              }, 500);
            });
          }
        });
      };

    });

}).call(this);
