// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name unuApp.controller:IngresantesCtrl
    * @description
    * # FacultadesCtrl
    * Controller of the unuApp
   */

  angular.module('unuApp').controller('IngresantesCtrl', [
'MessageFactory', '$rootScope', '$scope', 'Restangular', '$mdDialog', '$timeout', 'ngTableParams', 'LxDialogService', 'ToastMD', '$mdBottomSheet', '$state',
  function(MessageFactory, $rootScope, $scope, Restangular, $mdDialog, $timeout, ngTableParams, LxDialogService, ToastMD, $mdBottomSheet, $state) {
    var List, service;

    $scope.UI = {
      refresh: false,
      message: MessageFactory,
      title: 'Listado de Ingresantes',
      editMode: false,
      selected: null,
      customActions:[]
    };

    var LOCAL ={
      name: 'Ingresante',
      form:'views/ingresantes/form.html',
      route:'ingresantes',
      route_periodos: 'periodos',
      route_facultades: 'facultades',
      route_modalidades: 'modalidadingresos',
      route_escuelas: 'escuelas'
    };
    service = Restangular.all(LOCAL.route);
    $rootScope.app.module = ' > ' + LOCAL.name;

    service.customGET('model/sexo', {}).then(function(result){
      $scope.sexo = result; //sexo = result;
    });
    service.customGET('model/tipodocumento', {}).then(function(result){
      $scope.tipodocumento = result;
    });

    var LoadFacultades = function LoadFacultades() {
      var serviceFacultad = Restangular.all(LOCAL.route_facultades);
      serviceFacultad.getList().then(function(data){
        $scope.facultades = data;
      });
    };
    var LoadPeriodos = function LoadPeriodos() {
      var servicePeriodo = Restangular.all(LOCAL.route_periodos);
      servicePeriodo.getList().then(function(data){
        $scope.periodos = data;
      });
    };
    var LoadModalidades = function LoadModalidades() {
      var serviceModalidad = Restangular.all(LOCAL.route_modalidades);
      serviceModalidad.getList().then(function(data){
        $scope.modalidades = data;
      });
    };

    List = function() {
      $scope.tableParams = new ngTableParams({
        page: 1,
        count: 10
      }, {
        total: 0,
        getData: function($defer, params) {
          var query;
          query = params.url();
          $scope.UI.refresh = true;
          service.customGET('methods/paginate', query).then(function(result) {
            $timeout(function() {
              params.total(result.total);
              $defer.resolve(result.data);
              $scope.UI.refresh = false;
            }, 500);
          });
        }
      });
      $scope.tableParams.settings({counts:[]});
    };

    $scope.Refresh = function Refresh(){
      $scope.UI.selected = null;
      $scope.UI.editMode = false;
      $scope.tableParams.reload();
    };

    $scope.New = function New($event){
      var parentEl = angular.element(document.body);
      $mdDialog.show({
        parent: parentEl,
        targetEvent: $event,
        templateUrl :LOCAL.form,
        locals:{
          service: service,
          name: LOCAL.name,
          sexo: $scope.sexo,
          tipodocumento: $scope.tipodocumento,
          periodos: $scope.periodos,
          facultades: $scope.facultades,
          modalidades: $scope.modalidades,
          route_escuelas: LOCAL.route_escuelas,
          table:$scope.tableParams
        },
        controller: 'IngresanteNewCtrl'
      });
    };
    $scope.Edit = function Edit($event){
      var parentEl = angular.element(document.body);
      //console.log($scope.periodos);
      $mdDialog.show({
        parent: parentEl,
        targetEvent: $event,
        templateUrl :LOCAL.form,
        locals:{
          name: LOCAL.name,
          sexo: $scope.sexo,
          tipodocumento: $scope.tipodocumento,
          periodos: $scope.periodos,
          facultades: $scope.facultades,
          modalidades: $scope.modalidades,
          route_escuelas: LOCAL.route_escuelas,
          table:$scope.tableParams,
          model: Restangular.copy($scope.UI.selected)
        },
        controller: 'IngresanteEditCtrl'
      });
    };

    $scope.Delete = function Delete($event){
      var confirm = $mdDialog.confirm()
          .title(LOCAL.name)
          .content(MessageFactory.Form.QuestionDelete)
          .ariaLabel(LOCAL.name)
          .targetEvent($event)
          .ok(MessageFactory.Buttons.Yes)
          .cancel(MessageFactory.Buttons.No);

      var selected = Restangular.copy($scope.UI.selected);
      $mdDialog.show(confirm).then(function() {
        selected.remove().then(function() {
          $scope.Refresh();
          ToastMD.success(MessageFactory.Form.Deleted);
        });
      }, function() {

      });
    };

    $scope.EnabledEdit =function EnabledEdit(item){
      $scope.UI.editMode = false;
      $scope.UI.selected = null;
      angular.forEach($scope.tableParams.data,function(element){
        if(item._id !== element._id){
          element.active = false;
        }
      });

      if( item.active ){
        $scope.UI.editMode = true;
        $scope.UI.selected = item;
        $scope.UI.selected.route = LOCAL.route;
      }
    };

    new List();
    new LoadPeriodos();
    new LoadFacultades();
    new LoadPeriodos();
    new LoadModalidades();
  }])

  .controller('IngresanteNewCtrl',['$scope', 'table', 'name', 'MessageFactory', '$mdDialog', 'service', 'ToastMD', 'Restangular', 'sexo', 'tipodocumento', 'periodos', 'facultades', 'route_escuelas', 'modalidades',
  function($scope, table, name, MessageFactory, $mdDialog, service, ToastMD, Restangular, sexo, tipodocumento, periodos, facultades, route_escuelas, modalidades){

    $scope.submited = false;
    $scope.title = MessageFactory.Form.New.replace('{element}',name);
    $scope.Buttons = MessageFactory.Buttons;
    $scope.message = MessageFactory.Form;
    $scope.periodos = periodos;
    $scope.facultades = facultades;
    $scope.periodos = periodos;
    $scope.modalidades = modalidades;
    $scope.sexo = sexo;
    $scope.tipodocumento = tipodocumento;


    $scope.LoadEscuelas = function LoadEscuelas(){
      var serviceEscuela = Restangular.all(route_escuelas);
      serviceEscuela.getList({conditions:{_facultad:$scope.model._facultad._id}, populate:'_facultad'}).then(function(data){
        $scope.escuelas = data;
      });
    };
    $scope.Save = function(form) {
      $scope.submited = true;
      $scope.model._escuela = $scope.model._escuela._id;

      if (form.$valid) {
        service.post($scope.model).then(function() {
          ToastMD.success(MessageFactory.Form.Saved);
          $mdDialog.hide();
          table.reload();
        });
      }
    };
    $scope.Cancel = function(){
      $mdDialog.hide();
    };

  }])

  .controller('IngresanteEditCtrl',['$scope', 'table', 'name', 'MessageFactory', 'model', 'ToastMD', '$mdDialog', 'Restangular', 'sexo', 'tipodocumento', 'periodos', 'facultades', 'route_escuelas', 'modalidades',
  function($scope, table, name, MessageFactory, model, ToastMD, $mdDialog, Restangular, sexo, tipodocumento, periodos, facultades, route_escuelas, modalidades){
    $scope.submited = false;
    $scope.LoadEscuelas = function LoadEscuelas(){
      var serviceEscuela = Restangular.all(route_escuelas);
      serviceEscuela.getList({conditions:{_facultad:$scope.model._facultad._id}, populate:'_facultad'}).then(function(data){
        $scope.escuelas = data;
      });
    };
    var serviceFacultad = Restangular.all('facultades');
    serviceFacultad.getList({conditions:{_id:model._escuela._facultad}}).then(function(data){
      model._facultad = data[0];
      $scope.LoadEscuelas();
    });

    $scope.model = model;
    $scope.title = MessageFactory.Form.Edit.replace('{element}',name);
    $scope.Buttons = MessageFactory.Buttons;
    $scope.facultades = facultades;
    $scope.periodos = periodos;
    $scope.modalidades = modalidades;
    $scope.sexo = sexo;
    $scope.tipodocumento = tipodocumento;

    $scope.Save = function(form) {
      $scope.submited = true;
      if (form.$valid) {
        $scope.model.put().then(function() {
          ToastMD.success(MessageFactory.Form.Updated);
          $mdDialog.hide();
          table.reload();
        });
      }
    };
    $scope.Cancel = function(){
      $mdDialog.hide();
    };
  }]);
}).call(this);
