// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name unuApp.controller:PagoIngresanteCtrl
    * @description
    * # FacultadesCtrl
    * Controller of the unuApp
   */

  angular.module('unuApp').controller('PagosIngresantesCtrl', [
'MessageFactory', '$rootScope', '$scope', 'Restangular', '$mdDialog', '$timeout', 'ngTableParams', 'LxDialogService', 'ToastMD', '$mdBottomSheet', '$state',
  function(MessageFactory, $rootScope, $scope, Restangular, $mdDialog, $timeout, ngTableParams, LxDialogService, ToastMD, $mdBottomSheet, $state) {
    var List, service;

    $scope.UI = {
      refresh: false,
      message: MessageFactory,
      title: 'Listado de Ingresantes',
      editMode: false,
      selected: null,
      customActions:[]
    };

    var LOCAL ={
      name: 'Pagos de Ingresantes',
      form_pago:'views/ingresantes/form_pago.html',
      form_pagogrupo: 'views/ingresantes/form_pagogrupo.html',
      route:'ingresantes',
      route_facultades: 'facultades',
      route_periodos: 'periodos',
      route_escuelas: 'escuelas'
    };
    service = Restangular.all(LOCAL.route);
    $rootScope.app.module = ' > ' + LOCAL.name;

    $scope.estados = [];
    $scope.estados.push({id: '', title:'Todos'});
    service.customGET('model/estado', {}).then(function(result){
      //$scope.estados = result;
      angular.forEach(result, function(val, key){
          $scope.estados.push({id: val, title: val});
      });
      console.log($scope.estados);
    });

    var LoadFacultades = function LoadFacultades() {
      var serviceFacultad = Restangular.all(LOCAL.route_facultades);
      serviceFacultad.getList().then(function(data){
        $scope.facultades = data;
      });
    };
    var LoadPeriodos = function LoadPeriodos() {
      var servicePeriodo = Restangular.all(LOCAL.route_periodos);
      servicePeriodo.getList().then(function(data){
        $scope.periodos = data;
      });
    };


    $scope.LoadEcuelas = function LoadEcuelas(){
      var serviceEscuela = Restangular.all('escuelas');
      serviceEscuela.getList({conditions:{_facultad:$scope.filter._facultad._id},populate:'_facultad'}).then(function(data){
        $scope.escuelas = data;
      });
    };


    $scope.List = function() {
        console.log("List");
      $scope.tableParams = new ngTableParams({
        page: 1,
        count: 10,
        filter: {
            _periodo: $scope.filter._periodo._id,
            _escuela:  $scope.filter._escuela._id,
        }
      }, {
        total: 0,
        getData: function($defer, params) {
          var query;
          query = params.url();
          $scope.UI.refresh = true;
          service.customGET('methods/paginate', query).then(function(result) {
            $timeout(function() {
              params.total(result.total);
              $defer.resolve(result.data);
              $scope.UI.refresh = false;
            }, 500);
          });
        }
      });
      $scope.tableParams.settings({counts:[]});
    };

    $scope.Refresh = function Refresh(){
      $scope.UI.selected = null;
      $scope.UI.editMode = false;
      $scope.tableParams.reload();
    };

    $scope.Payment = function Payment($event){
      var parentEl = angular.element(document.body);
      $mdDialog.show({
        parent: parentEl,
        targetEvent: $event,
        templateUrl :LOCAL.form_pago,
        locals:{
          service: service,
          name: LOCAL.name,
          table:$scope.tableParams,
          model: Restangular.copy($scope.UI.selected)
        },
        controller: 'PagoIngresanteIndividualCtrl'
      });
    };

    $scope.GroupPayment = function GroupPayment($event){
      var parentEl = angular.element(document.body);
      $mdDialog.show({
        parent: parentEl,
        targetEvent: $event,
        templateUrl :LOCAL.form_pagogrupo,
        locals:{
          service: service,
          name: LOCAL.name,
          table:$scope.tableParams
        },
        controller: 'PagoIngresanteGrupoCtrl'
      });
    };

    $scope.EnabledEdit =function EnabledEdit(item){
      $scope.UI.editMode = false;
      $scope.UI.selected = null;
      angular.forEach($scope.tableParams.data,function(element){
        if(item._id !== element._id){
          element.active = false;
        }
      });

      if( item.active ){
        $scope.UI.editMode = true;
        $scope.UI.selected = item;
        $scope.UI.selected.route = LOCAL.route;
      }
    };

    //new List();
    new LoadFacultades();
    new LoadPeriodos();

  }])
  .controller('PagoIngresanteIndividualCtrl',['$scope', 'table', 'name', 'MessageFactory', '$mdDialog', 'service', 'ToastMD', 'Restangular', 'model',
  function($scope, table, name, MessageFactory, $mdDialog, service, ToastMD, Restangular, model){
    $scope.submited = false;
    $scope.title = MessageFactory.Form.New.replace('{element}',name);
    $scope.Buttons = MessageFactory.Buttons;
    $scope.message = MessageFactory.Form;
    $scope.model = model;
    $scope.model.nombrecompleto = model.nombres + ' ' + model.apellidoPaterno;
    $scope.Save = function(form) {
      $scope.submited = true;

      if (form.$valid) {
        service.post($scope.model).then(function() {
          ToastMD.success(MessageFactory.Form.Saved);
          $mdDialog.hide();
          table.reload();
        });
      }
    };
    $scope.Cancel = function(){
      $mdDialog.hide();
    };

  }])
  .controller('PagoIngresanteGrupoCtrl',['$scope', 'table', 'name', 'MessageFactory', '$mdDialog', 'service', 'ToastMD', 'Restangular',
  function($scope, table, name, MessageFactory, $mdDialog, service, ToastMD, Restangular){
    $scope.submited = false;
    $scope.title = MessageFactory.Form.New.replace('{element}',name);
    $scope.Buttons = MessageFactory.Buttons;
    $scope.message = MessageFactory.Form;

    $scope.Save = function(form) {
      $scope.submited = true;

      if (form.$valid) {
        service.post($scope.model).then(function() {
          ToastMD.success(MessageFactory.Form.Saved);
          $mdDialog.hide();
          table.reload();
        });
      }
    };
    $scope.Cancel = function(){
      $mdDialog.hide();
    };

  }]);
}).call(this);
