// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';

  /**
    * @ngdoc service
    * @name unuApp.AuthInterceptor
    * @description
    * # AuthInterceptor
    * Service in the unuApp.
   */
  angular.module('unuApp').service('AuthInterceptor', ['AuthTokenFactory',function(AuthTokenFactory) {
    return {
      request: function(config) {
        var token;
        token = AuthTokenFactory.getToken();
        if (token) {
          config.headers = config.headers || {};
          config.headers.Authorization = 'unu ' + token;
        }
        return config;
      }
    };
  }]);

}).call(this);
