// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name unuApp.controller:AboutCtrl
    * @description
    * # AboutCtrl
    * Controller of the unuApp
   */
  angular.module('unuApp').controller('SidenavCtrl', function($scope,$rootScope) {
    console.log($rootScope.menu);
    this.autoFocusContent = false;

    this.isOpen = function isOpen(){
      //alert("Open");
    };
    $scope.close = function() {
      return $mdSidenav('left').toggle().then(function() {
        $log.debug('close sidenav');
      });
    };
    $scope.toggle = function() {
      return $mdSidenav('left').toggle().then(function() {
        $log.debug('close sidenav');
      });
    };
    $scope.toggleMenu = function() {
      alert("ok toggle...");
    };

  });

}).call(this);
