// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name unuApp.controller:AboutCtrl
    * @description
    * # AboutCtrl
    * Controller of the unuApp
   */
angular.module('unuApp').controller('SidenavCtrl', ['$scope','$rootScope','$mdSidenav',function($scope,$rootScope,$mdSidenav) {
    //console.log($rootScope.menu);

    this.autoFocusContent = false;

    this.isOpen = function isOpen(){
      //alert("Open");
    };
    $scope.close = function() {
      return $mdSidenav('left').toggle().then(function() {
      });
    };
    $scope.toggle = function() {
      return $mdSidenav('left').toggle().then(function() {
      });
    };
    $scope.toggleMenu = function() {
    };

  }]);

}).call(this);
